# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d26113f66c447238285293fd4c239a979d44252a44ac79bb0997450640058b7be45dbd4d88835f8a49681b1f06f82ecd263824d3ef60da61da79e07637a7ea62

test:
  secret_key_base: b564851cb83b0203481569596f3bd5e6c09c2c8d299f160a6162a91abb89dfa7a3ba6725fa78cc58275699d4fc3d9c5c8984c19ba88db1387eeb278717ff6351

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
